---
- name: Copy prometheus config file
  ansible.builtin.template:
    src: 'configs/prometheus.yml.j2'
    dest: '{{ prometheus.config_dir }}/prometheus.yml'
    force: true
    owner: prometheus
    group: prometheus
    mode: '664'
  notify: Prometheus restart
