---
- name: Copy prometheus config file
  ansible.builtin.template:
    src: 'configs/prometheus.yml.j2'
    dest: '{{ prometheus.config_dir }}'
    force: true
    owner: root
    group: prometheus
    mode: '640'
  notify: Prometheus restart
