---
- name: Get and unarchive prometheus-nginxlog-exporter
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ prometheus-nginxlog-exporter.url }}"
    dest: '/tmp/'

- name: Copy prometheus-nginxlog-exporter bin
  ansible.builtin.copy:
    remote_src: true
    src: '/tmp/{{ prometheus-nginxlog-exporter.unarchive_dir }}/prometheus-nginxlog-exporter'
    dest: '{{ system.binary_dir }}/prometheus-nginxlog-exporter'
    owner: prometheus
    mode: '755'

- name: Open firewalld ports
  ansible.posix.firewalld:
    port: "{{ prometheus-nginxlog-exporter.port }}/tcp"
    state: enabled
    immediate: true
    permanent: true

- name: Copy service
  ansible.builtin.template:
    src: 'services/prometheus-nginxlog-exporter.service.j2'
    dest: '/etc/systemd/systemd/system/prometheus-nginxlog-exporter.service'
    mode: '644'
    force: true
  notify: Systemd daemon reload
