---
# tasks file for monitoring

- name: Add group
  ansible.builtin.group:
    name: "prometheus"
    state: present
    system: true

- name: Add user
  ansible.builtin.user:
    name: "prometheus"
    group: "prometheus"
    create_home: false
    shell: "/usr/sbin/nologin"
    system: true
    state: present
    home: "{{ prometheus.db_dir }}"

- name: Install node_exporter
  ansible.builtin.include_tasks:
    file: setup_node_exporter.yml

- name: Install nginxlog_exporter
  ansible.builtin.include_tasks:
    file: setup_nginxlog_exporter.yml

- name: Install prometheus
  ansible.builtin.include_tasks:
    file: install_prometheus.yml

- name: Configure prometheus
  ansible.builtin.include_tasks:
    file: configure_prometheus.yml
