#cloud-config
# package_update: true
# package_upgrade: true
packages:
  - git
  - ansible

runcmd:
  - [su, ansible, -c, "git clone https://github.com/a-sotnikov/diplom_ansible.git /home/ansible/diplom/"]

users:
- name: ansible
  gecos: Ansible User
  shell: /bin/bash
  groups: users,admin,wheel
  sudo: ALL=(ALL) NOPASSWD:ALL
  ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd9Mt6Erg0XhbKH3Z43qsTPi4D6f4XMw9613UgMmR8guas+EchpdK0fiH2OeQsROW7hiUgqByzT8bCJlg6qHcP0ssodRFC9p8YHkwmI+faEzDsZguUwW++vD5iXY4RZjjf14qGXc+23Orj3SPBSvbf2tJ/6ZCYBFrIC17MY9yY3dyDeTUOPB6meuf2ibaU8RJG6lqL6T1zVY6R/Yb8IIr72YzP4aK1xLpa+LsAKjVj4PGCiWieAN7XS9QMhreSdDxnYV5t3h14qbzPKpG/o2c+lVpevln6/zcetM1eHlaADLpwdy1+vnxJi5PItUU6whPwAiB2BE7EXvp/vrVQ0RW8oYSZtKZSmVitobueLnnftfVONHdvmQ7hxJE92n+ZAwTeUVygk252bTaoXXBfuA9S8v0lY5LPuK+E16lJUVv+KX8+UY475XLZfsYgdXAM4JsSlTMw7pxxeERWJdJReWXUfXmJd8YLHPATEZYefGogir7ipe9xSyr8j7OAmLmXvw0= andy@redmi-win
