---
# tasks file for web_servers
- name: Install NGINX
  ansible.builtin.include_tasks:
    file: setup_nginx.yml

- name: Open firewalld ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: enabled
    immediate: true
    permanent: true
  loop:
    - '{{ nginx.port }}/tcp'
    - '{{ node_exporter.port }}/tcp'
    - '{{ nginxlog_exporter.port }}/tcp'

- name: Start and enable services
  ansible.builtin.systemd:
    service: "{{ item }}"
    state: started
    enabled: true
  loop:
    - 'nginx'
    - 'node_exporter'
    - 'prometheus-nginxlog-exporter'
