---
# tasks file for web_servers

- name: Install nginx
  when: not nginx.skip_install
  block:

  - name: Update dnf and install nginx
    ansible.builtin.dnf:
      # update_cache: true
      name: nginx-{{ nginx.version }}
      state: present

  - name: Open firewalld ports
    ansible.posix.firewalld:
      port: "{{ nginx.port }}/tcp"
      state: enabled
      immediate: true
      permanent: true

- name: Update UI
  ansible.builtin.copy:
    src: 'static/'
    dest: '/usr/share/nginx/html/'
    owner: nginx
    mode: '600'
  notify: Restart nginx
