---
- name: Check is node_exporter already installed
  ansible.builtin.stat:
    path: '/etc/systemd/system/node_exporter.service'
  register: node_exporter_service

- name: Get and unarchive node_exporter
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ node_exporter.url }}"
    dest: '/tmp/'
  when: not node_exporter_service.stat.exists

- name: Copy node_exporter bin
  ansible.builtin.copy:
    remote_src: true
    src: '/tmp/{{ node_exporter.unarchive_dir }}/node_exporter'
    dest: '{{ node_exporter.binary_dir }}/node_exporter'
    owner: monitoring
    mode: '755'
  when: not node_exporter_service.stat.exists

- name: Copy service
  ansible.builtin.template:
    src: 'node_exporter.service.j2'
    dest: '/etc/systemd/systemd/system/node_exporter.service'
    mode: '755'
  notify: Systemd daemon reload
