---
- name: Update dnf and install nginx
  ansible.builtin.dnf:
    update_cache: true
    name: nginx
    state: present

- name: Update UI
  ansible.builtin.copy:
    src: 'static/'
    dest: '/usr/share/nginx/html/'
    owner: nginx
    mode: '600'
  notify: Restart nginx
