- name: Setup monitoring
  hosts: all
  gather_facts: false
  become: true
  vars_files: config.yml

  tasks:
    - name: Add group
      ansible.builtin.group:
        name: "prometheus"
        state: present
        system: true

    - name: Add user
      ansible.builtin.user:
        name: "prometheus"
        group: "prometheus"
        create_home: false
        shell: "/usr/sbin/nologin"
        system: true
        state: present
        home: "{{ prometheus.db_dir }}"

    - name: Check if prometheus already installed
      ansible.builtin.stat:
        path: '/etc/systemd/system/prometheus.service'
      register: prometheus_service

    - name: Get and install prometheus
      when: not prometheus_service.stat.exists
      block:

        - name: Create prometheus configuration directories
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            owner: root
            group: prometheus
            mode: '770'
          with_items:
            - "{{ prometheus.config_dir }}"
            - "{{ prometheus.config_dir }}/rules"
            - "{{ prometheus.config_dir }}/file_sd"

        - name: Get prometheus binaries
          ansible.builtin.unarchive:
            remote_src: true
            src: "{{ prometheus.url }}"
            dest: '/tmp'

        - name: Install prometheus binaries
          ansible.builtin.copy:
            remote_src: true
            src: "/tmp/{{ prometheus.unarchive_dir }}/{{ item }}"
            dest: "{{ prometheus.binary_dir }}/{{ item }}"
            mode: '755'
            owner: root
            group: root
          with_items:
            - 'prometheus'
            - 'promtool'

        - name: Install prometheus console templates
          ansible.builtin.copy:
            remote_src: true
            src: "/tmp/{{ prometheus.unarchive_dir }}/{{ item }}"
            dest: "{{ prometheus.config_dir }}/{{ item }}"
            mode: '644'
            owner: root
            group: root
          with_items:
            - 'console_libraries'
            - 'consoles'

        - name: Copy prometheus service file
          ansible.builtin.template:
            src: 'prometheus.service.j2'
            dest: '/etc/systemd/system/prometheus.service'
            owner: root
            group: root
            mode: '644'
          notify: Systemd daemon reload

    - name: Copy prometheus config file
      ansible.builtin.template:
        src: 'prometheus.yml.j2'
        dest: '{{ prometheus.config_dir }}'
        force: true
        owner: root
        group: prometheus
        mode: '640'
      notify: Prometheus restart
