- name: Setup webservers
  hosts: all
  gather_facts: false
  become: true
  roles:
    - web_servers
  vars_files: config.yml

- name: Setup monitoring
  hosts: all
  gather_facts: false
  become: true
  roles:
    - monitoring
  vars_files: config.yml
